spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shwetadhane/cloud-config-server

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.3:8761/eureka/
  instance:
    preferIpAddress: true
